### ISSUE TITLE
How to configure ZWave lock?

### ISSUE THREAD

**Issue by Pltnorwich** [vojtamolda/homebridge-bluetooth#11]
Hi,

I've been hoping to connect my lock via bluetooth (which it currently uses on my phone) instead of zwave - as this seemed to drain the battery really quick.

installed _homebridge_ and it started ok, thermostat loaded........
installed _homebridge-bluetooth_

When i went to start home bridge it failed with the following:
```
Load homebridge-bluetooth.Bluetooth
/usr/local/lib/node_modules/homebridge-bluetooth/source/platform.js:16
  if (!config.accessories || !(config.accessories instanceof Array)) {
             ^
TypeError: Cannot read property 'accessories' of null
    at new BluetoothPlatform (/usr/local/lib/node_modules/homebridge-bluetooth/source/platform.js:16:14)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

1) How can i get home bridge started (maybe disabling bluetooth as and when)
2) How do i go about adding my lock to home bridge? I managed to get my thermostat connected with a lot of copy past in the config file but i would know what i need to add for the lock.

Phil

**Comment by vojtamolda** [comment]
Hello Phil,

Thanks for your question and for your interest in the plugin. 

1) I think the reason why _Homebridge_ won't start is that you didn't update your `~/.homebridge/config.json` configuration file. See [the example](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/config.json) for inspiration.

2) I'm assuming you're using SmartThings hub to control your _ZWave_ lock. If that's the case [homebridge-smartthings](https://github.com/pdlove/homebridge-smartthings) plugin might be your best bet to make it talk to _HomeKit_.

**Comment by Pltnorwich** [comment]
Hi Vojtamolda,

Im using a raspberry pi, with bluetooth dongle an UZB 1 stick, i was using the zway-homebridge plugin, but found the lock drain 30% in a few weeks, using bluetooth its lasted about 18months. So I would like to use the bluetooth of the lock to talk to the raspberry pi, then home bridge.

Im unsure of what data I would need in the json file for a lock. 

Thanks

**Comment by vojtamolda** [comment]
You'd need BLE service and characteristics UUIDs of the lock. You can get these, for instance, by using the [LightBlue Explorer](https://itunes.apple.com/us/app/lightblue-explorer-bluetooth-low-energy/id557428110?mt=8) iOS app.

I'm not sure what communication protocol does the lock use, but it needs to match the _HomeKit_ `LockMechanism` service (full description is [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2959)) and all of it's mandatory characteristics.


The `config.json` would look something like this (snippet from the [Lock example](https://github.com/vojtamolda/homebridge-bluetooth/tree/master/examples/lock) `config.json` file):

```
"name": "ZWave Lock",
"address": "01:23:45:67:89:AB",
"services": [ {
    "name": "Lock",
    "type": "LockMechanism",
    "UUID": "LOCK-MECHANISM-SERV-UUID-HERE",
    "characteristics": [ {
        "type": "LockTargetState",
        "UUID": "LOCK-TAGET-STATE-CHAR-UUID-HERE"
      }, {
        "type": "LockCurrentState",
        "UUID": "LOCK-CURRENT-STATE-CHAR-UUID-HERE"
      } ]
   } ]
```

**Comment by Pltnorwich** [comment]
Ahhhh thats really helpful thank you

I will get the app and have a look, I may ask more questions later. 

Ive been googling bluetooth lock json files to see what i could find.

Much appreciated

**Comment by Pltnorwich** [comment]
Hi,
This is my json file - it has no errors on checker; I want to use the bluetooth of the lock and will disable zwave in the server
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "xxx"
	},

	"description": "Thermostat",

	"accessories": [{
		"accessory": "TADO",
		"name": "Tado",
		"homeID": "xxx",
		"username": "xxx",
		"password": "xxx"
	}, {


		"address": "CB:D3:D9:EC:4D:C5",
		"services": [{
			"name": "Front Door",
			"type": "LockMechanism",
			"UUID": "DCFF0001xxx",
			"characteristics": [{
				"type": "LockTargetState",
				"UUID": "DCFF0003xxx"
			}, {

				"type": "LockCurrentState",
				"UUID": "DCFF0002xxx"
			}, {




				"platforms": [{
					"platform": "ZWayServer",
					"url": "http://xxx:8083/",
					"login": "xx",
					"password": "xxxxx"
				}]
			}]
		}]
	}]
}
```
I have bluetooth driver installed and is running but get the following error when running homebridge;
```
 hci onSocketError: Operation not permitted +5ms
  hci read bd addr - writing: 01091000 +8ms
[4/22/2017, 12:27:52 PM] Registering platform 'homebridge-bluetooth.Bluetooth'
[4/22/2017, 12:27:52 PM] ---
[4/22/2017, 12:27:53 PM] Loaded plugin: homebridge-tadoheating
[4/22/2017, 12:27:53 PM] Registering accessory 'homebridge-tado.TADO'
[4/22/2017, 12:27:53 PM] ---
[4/22/2017, 12:27:59 PM] Loaded plugin: homebridge-zway
[4/22/2017, 12:27:59 PM] Registering accessory 'homebridge-zway.ZWayServer'
[4/22/2017, 12:27:59 PM] Registering platform 'homebridge-zway.ZWayServer'
[4/22/2017, 12:27:59 PM] ---
[4/22/2017, 12:27:59 PM] Loaded config.json with 2 accessories and 0 platforms.
[4/22/2017, 12:27:59 PM] ---
[4/22/2017, 12:27:59 PM] Loading 2 accessories...
[4/22/2017, 12:27:59 PM] [Tado] Initializing TADO accessory...
  hci set scan enabled - writing: 010c20020001 +7s
  hci onSocketError: Operation not permitted +6ms
/usr/local/lib/node_modules/homebridge/lib/api.js:46
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I thought homebridge would just use the info provided in the json file (lock address) to then display it.

**Comment by Pltnorwich** [comment]
Ive ran it as sudo and get less errors (ran in debug mode before).
```
[4/22/2017, 1:39:53 PM] [Tado] Initializing TADO accessory...
  hci set scan enabled - writing: 010c20020001 +7s
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Danalock' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
Surely with the homebridge-bluetooth I don't need to add a plugin?

**Comment by vojtamolda** [comment]
I think the problem above is caused by an error in the `config.json` file not related to this plugin. _Homebridge_ couldn't find the `TADO` plugin that would be able to access an accessory defined in the config file.

Besides the problem above, I think you can't run both `homebridge-zwave` and `homebridge-bluetooth` plugin at the same time. Both require access to the BLE hardware on the _Raspberry_ and will almost certainly run into a conflict.

**Comment by Pltnorwich** [comment]
Hi vojtamolda,
Without the Bluetooth plugin homebridge works fine including tado. 
Maybe you are correct that zwave and Bluetooth on homebridge can not run, how can I disable homebridge-zwave?
The zway server was using the zway stick (separate from Bluetooth) but I can give it a go without zwave if you know how I can disable zway server starting and homebridge-zway with uninstalling it all....?

Thanks

**Comment by vojtamolda** [comment]
Sorry. No idea. I don't use zway.

**Comment by Pltnorwich** [comment]
Ok, maybe I should try a new install of just homebridge the  Bluetooth plugin and report back.
