### ISSUE TITLE
Problem restarting Homebridge

### ISSUE THREAD

**Issue by sweetlime05** [vojtamolda/homebridge-bluetooth#29]
If you restart the homebridge after installing the plug-in, the same content is repeated in the log and will not run.

[3/26/2020, 8:32:20 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[3/26/2020, 8:32:25 PM] [HB Supervisor] Restarting Homebridge...
[3/26/2020, 8:32:25 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[3/26/2020, 8:32:25 PM] [HB Supervisor] Started Homebridge with PID: 2335
[3/26/2020, 8:32:29 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/26/2020, 8:32:29 PM] ---
[3/26/2020, 8:32:29 PM] Loaded plugin: homebridge-bluetooth
Homebridge API version: 2.4
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'bluetooth-hci-socket'
Require stack:
- /usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/hci-socket/hci.js
- /usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/hci-socket/bindings.js
- /usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/resolve-bindings.js
- /usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/index.js
- /usr/lib/node_modules/homebridge-bluetooth/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/hci-socket/hci.js',
    '/usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/hci-socket/bindings.js',
    '/usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/resolve-bindings.js',
    '/usr/lib/node_modules/homebridge-bluetooth/node_modules/noble/index.js',
    '/usr/lib/node_modules/homebridge-bluetooth/index.js',
    '/usr/lib/node_modules/homebridge/lib/plugin.js',
    '/usr/lib/node_modules/homebridge/lib/server.js',
    '/usr/lib/node_modules/homebridge/lib/cli.js',
    '/usr/lib/node_modules/homebridge/bin/homebridge'
  ]
}

**Comment by vojtamolda** [comment]
Hello @sweetlime05,

I'd love to investigate this but unfortunately I don't have time. The source code is available so hopefully a combination of reading and googling will get you on the right track ;)

Sorry for my late response and for not being too helpful. Good luck!

Vojta

**Comment by Stetocasa** [comment]
same issue. Copy and paste
